format= """$username@$hostname $all$directory
$character"""
scan_timeout = 10
add_newline = true
[character]
success_symbol = "[ﬦ](bold green)"
error_symbol = "[ﬦ](bold red)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[username]
style_user = "bold dimmed green"
format = "[$user]($style)"
show_always = true
